package zinsrechner;

import java.text.NumberFormat;

/**
 *
 * @author cstift
 */
public class Hauptrechner extends javax.swing.JFrame {

    public Hauptrechner() {
        initComponents();
        FieldResult.disable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelStartingCapital = new javax.swing.JLabel();
        LabelInterest = new javax.swing.JLabel();
        LabelTime = new javax.swing.JLabel();
        LabelResult = new javax.swing.JLabel();
        ButtonCalculate = new javax.swing.JButton();
        FieldResult = new javax.swing.JTextField();
        LabelAfterStartingCapital = new javax.swing.JLabel();
        LabelAfterInterest = new javax.swing.JLabel();
        LabelAfterTime = new javax.swing.JLabel();
        LabelAfterResult = new javax.swing.JLabel();
        LabelTitle = new javax.swing.JLabel();
        LabelWarnings = new javax.swing.JLabel();
        FieldStartingCapital = new javax.swing.JFormattedTextField();
        FieldInterest = new javax.swing.JFormattedTextField();
        FieldTime = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelStartingCapital.setText("Anfangskapital");

        LabelInterest.setText("Zinssatz");

        LabelTime.setText("Laufzeit");

        LabelResult.setText("Endkapital");

        ButtonCalculate.setText("Berechnen");
        ButtonCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCalculateActionPerformed(evt);
            }
        });

        LabelAfterStartingCapital.setText("EUR");

        LabelAfterInterest.setText("% p.a.");

        LabelAfterTime.setText("Jahre");

        LabelAfterResult.setText("EUR");

        LabelTitle.setText("Fäncy Zinsrechner!");

        FieldStartingCapital.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        FieldStartingCapital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldStartingCapitalActionPerformed(evt);
            }
        });

        FieldInterest.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.##"))));
        FieldInterest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldInterestActionPerformed(evt);
            }
        });

        FieldTime.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        FieldTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldTimeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LabelTime)
                                    .addComponent(LabelInterest)
                                    .addComponent(LabelStartingCapital)
                                    .addComponent(LabelResult))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(FieldResult, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                    .addComponent(ButtonCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(FieldStartingCapital)
                                    .addComponent(FieldInterest)
                                    .addComponent(FieldTime))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelAfterStartingCapital)
                                    .addComponent(LabelAfterInterest)
                                    .addComponent(LabelAfterTime)
                                    .addComponent(LabelAfterResult)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(LabelWarnings, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(LabelTitle)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(LabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelStartingCapital)
                    .addComponent(LabelAfterStartingCapital)
                    .addComponent(FieldStartingCapital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelInterest)
                    .addComponent(LabelAfterInterest)
                    .addComponent(FieldInterest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelTime)
                    .addComponent(LabelAfterTime)
                    .addComponent(FieldTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelResult)
                    .addComponent(FieldResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelAfterResult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonCalculate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelWarnings, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCalculateActionPerformed
        double startCapital = ((Number)FieldStartingCapital.getValue()).doubleValue();
        double interest = ((Number)FieldInterest.getValue()).doubleValue();
        double time =  ((Number)FieldTime.getValue()).doubleValue();
        double result = Calculator.calculate(startCapital, interest, time);
        FieldResult.setText(Double.toString(result));
    }//GEN-LAST:event_ButtonCalculateActionPerformed

    private void FieldStartingCapitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldStartingCapitalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldStartingCapitalActionPerformed

    private void FieldInterestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldInterestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldInterestActionPerformed

    private void FieldTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldTimeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCalculate;
    private javax.swing.JFormattedTextField FieldInterest;
    private javax.swing.JTextField FieldResult;
    private javax.swing.JFormattedTextField FieldStartingCapital;
    private javax.swing.JFormattedTextField FieldTime;
    private javax.swing.JLabel LabelAfterInterest;
    private javax.swing.JLabel LabelAfterResult;
    private javax.swing.JLabel LabelAfterStartingCapital;
    private javax.swing.JLabel LabelAfterTime;
    private javax.swing.JLabel LabelInterest;
    private javax.swing.JLabel LabelResult;
    private javax.swing.JLabel LabelStartingCapital;
    private javax.swing.JLabel LabelTime;
    private javax.swing.JLabel LabelTitle;
    private javax.swing.JLabel LabelWarnings;
    // End of variables declaration//GEN-END:variables
}
